"""add language to posts

Revision ID: 55131e851a2f
Revises: 4d08b726a930
Create Date: 2022-11-24 01:20:20.590987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55131e851a2f'
down_revision = '4d08b726a930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
